tilemapFilesInfo = [
  {
    "name": "basic_room_000",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_001",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_002",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_003",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemPrep": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "basic_room_004",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_005",
    "tags": {
      "directionRequired": "sw",
      "fromE": "",
      "fromN": "",
      "fromS": "sw",
      "fromW": "sw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "basic_room_006",
    "tags": {
      "fromE": "",
      "fromN": "",
      "fromS": "sw",
      "fromW": "sw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 4
  },
  {
    "name": "basic_room_007",
    "tags": {
      "directionRequired": "nw",
      "fromE": "",
      "fromN": "nw",
      "fromS": "",
      "fromW": "nw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitN",
      "WallW",
      "WallN",
      "WallBombW",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleN",
      "LockW",
      "LockN",
      "NoEntryW",
      "NoEntryN",
      "OneWayW",
      "OneWayN",
      "BossLockW",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "basic_room_008",
    "tags": {
      "fromE": "",
      "fromN": "",
      "fromS": "s",
      "fromW": "",
      "itemRequired": "roc1",
      "letter": "n,ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitS",
      "WallBombS",
      "WallBombVisibleS",
      "LockS",
      "NoEntryS",
      "OneWayS",
      "BossLockS"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "basic_room_009",
    "tags": {
      "exitRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "basic_room_010",
    "tags": {
      "entranceRequired": "s",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "basic_room_011",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitE",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_012",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_013",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_014",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_015",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_016",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_017",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "ExitW",
      "WallS",
      "ExitE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_018",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_019",
    "tags": {
      "exitRequired": "ns",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 2
  },
  {
    "name": "basic_room_020",
    "tags": {
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallS",
      "WallN",
      "WallBombS",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleN",
      "LockS",
      "LockN",
      "NoEntryS",
      "NoEntryN",
      "OneWayS",
      "OneWayN",
      "BossLockS",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 4
  },
  {
    "name": "basic_room_021",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_022",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "n,ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitE",
      "ObstaclePitS",
      "WallW",
      "WallS",
      "WallE",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "LockW",
      "LockS",
      "LockE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "BossLockW",
      "BossLockS",
      "BossLockE"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "basic_room_023",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "basic_room_024",
    "tags": {
      "directionRequired": "e",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemPrep": "roc1,bracelet1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "ObstaclePitW",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "basic_room_025",
    "tags": {
      "directionRequired": "nesw",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 4
  },
  {
    "name": "basic_room_026",
    "tags": {
      "directionRequired": "nw",
      "fromE": "",
      "fromN": "nw",
      "fromS": "",
      "fromW": "nw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Enemies",
      "Chest",
      "ObstaclePitW",
      "ObstaclePitN",
      "WallW",
      "WallN",
      "WallBombW",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleN",
      "LockW",
      "LockN",
      "NoEntryW",
      "NoEntryN",
      "OneWayW",
      "OneWayN",
      "BossLockW",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "basic_room_027",
    "tags": {
      "directionRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "ExitW",
      "ExitS",
      "ExitE",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "bl_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bl_02",
    "tags": {
      "exitRequired": "e",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 2
  },
  {
    "name": "bl_03",
    "tags": {
      "exitRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "Enemies"
    ],
    "chest": false,
    "complexity": 2
  },
  {
    "name": "bl_04",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "bracelet1",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 3
  },
  {
    "name": "bl_05",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bl_06",
    "tags": {
      "exitRequired": "n",
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallS",
      "WallN",
      "NoEntryS",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 5
  },
  {
    "name": "bl_07",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bl_08",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bl"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bm_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bm"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bm_02",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bm"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bm_03",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bm"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bm_04",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bm"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "bm_05",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "bm"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "ExitW",
      "ExitS",
      "ExitE",
      "ExitN",
      "Enemies",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "e_01",
    "tags": {
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "letter": "e"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "e_02",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "e"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "WallW",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "e_03",
    "tags": {
      "exitRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "e"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "WallW",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 2
  },
  {
    "name": "e_04",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "e"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "WallW",
      "WallE",
      "WallBombW",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "LockW",
      "LockE",
      "NoEntryW",
      "NoEntryE",
      "OneWayW",
      "OneWayE",
      "BossLockW",
      "BossLockS",
      "BossLockE"
    ],
    "chest": false,
    "complexity": 2
  },
  {
    "name": "e_05",
    "tags": {
      "exitRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "e"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "ExitW",
      "ExitE",
      "ExitN",
      "WallBombW",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 2
  },
  {
    "name": "g_01",
    "tags": {
      "fromE": "",
      "fromN": "n",
      "fromS": "",
      "fromW": "",
      "letter": "g"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "Decoration",
      "NoEntryN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "g_02",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "g"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallDecorationS",
      "WallE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "g_03",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "g"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "WallW",
      "WallS",
      "WallE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "g_04",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "g"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "WallW",
      "WallS",
      "WallE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "g_05",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "g"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Decoration",
      "Chest",
      "WallW",
      "WallS",
      "WallE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "ib_01",
    "tags": {
      "fromE": "ew",
      "fromN": "",
      "fromS": "",
      "fromW": "ew",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitE",
      "WallW",
      "WallE",
      "WallBombW",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "LockW",
      "LockE",
      "NoEntryW",
      "NoEntryE",
      "OneWayW",
      "OneWayE",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_02",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "ib_03",
    "tags": {
      "fromE": "",
      "fromN": "n",
      "fromS": "",
      "fromW": "",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitN",
      "WallN",
      "WallBombN",
      "WallBombVisibleN",
      "LockN",
      "NoEntryN",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_04",
    "tags": {
      "entranceRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "roc1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_05",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 0
  },
  {
    "name": "ib_06",
    "tags": {
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitS",
      "ObstaclePitN",
      "ExitS",
      "ExitN",
      "WallBombS",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleN",
      "LockS",
      "LockN",
      "NoEntryS",
      "NoEntryN",
      "OneWayS",
      "OneWayN",
      "BossLockS",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_07",
    "tags": {
      "entranceRequired": "s",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemPrep": "roc1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 2
  },
  {
    "name": "ib_08",
    "tags": {
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitS",
      "ObstaclePitN",
      "WallS",
      "WallN",
      "WallBombS",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleN",
      "LockS",
      "LockN",
      "NoEntryS",
      "NoEntryN",
      "OneWayS",
      "OneWayN",
      "BossLockS",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_09",
    "tags": {
      "fromE": "nes",
      "fromN": "nes",
      "fromS": "nes",
      "fromW": "",
      "itemRequired": "bracelet1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallS",
      "WallE",
      "WallN",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_10",
    "tags": {
      "fromE": "esw",
      "fromN": "",
      "fromS": "esw",
      "fromW": "esw",
      "itemRequired": "roc1,bracelet1,bomb1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "LockW",
      "LockS",
      "LockE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "BossLockW",
      "BossLockS",
      "BossLockE"
    ],
    "chest": true,
    "complexity": 7
  },
  {
    "name": "ib_11",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "shield1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 2
  },
  {
    "name": "ib_12",
    "tags": {
      "directionRequired": "sw",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "roc1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 4
  },
  {
    "name": "ib_13",
    "tags": {
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallS",
      "WallN",
      "WallBombS",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleN",
      "LockS",
      "LockN",
      "NoEntryS",
      "NoEntryN",
      "OneWayS",
      "OneWayN",
      "BossLockS",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_14",
    "tags": {
      "fromE": "e",
      "fromN": "",
      "fromS": "",
      "fromW": "",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "ObstaclePitE",
      "WallBombE",
      "WallBombVisibleE",
      "NoEntryE"
    ],
    "chest": true,
    "complexity": 3
  },
  {
    "name": "ib_15",
    "tags": {
      "fromE": "e",
      "fromN": "",
      "fromS": "",
      "fromW": "",
      "itemBanned": "roc1",
      "itemRequired": "bomb1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitE",
      "WallBombE",
      "WallBombVisibleE",
      "NoEntryE"
    ],
    "chest": true,
    "complexity": 6
  },
  {
    "name": "ib_16",
    "tags": {
      "fromE": "",
      "fromN": "",
      "fromS": "s",
      "fromW": "",
      "itemRequired": "bomb1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "Decoration",
      "ObstaclePitS",
      "WallBombS",
      "WallBombVisibleS",
      "NoEntryS"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "iq_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemPrep": "roc1",
      "letter": "iq"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "item_roc1_01",
    "tags": {
      "directionRequired": "nw",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 4
  },
  {
    "name": "item_roc1_02",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 3
  },
  {
    "name": "item_roc1_03",
    "tags": {
      "directionRequired": "w",
      "fromE": "ew",
      "fromN": "",
      "fromS": "",
      "fromW": "ew",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "WallW",
      "WallE",
      "WallBombW",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "LockW",
      "LockE",
      "NoEntryW",
      "NoEntryE",
      "OneWayW",
      "OneWayE",
      "BossLockW",
      "BossLockE"
    ],
    "chest": true,
    "complexity": 6
  },
  {
    "name": "item_roc1_04",
    "tags": {
      "fromE": "ew",
      "fromN": "",
      "fromS": "",
      "fromW": "ew",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "Decoration",
      "WallW",
      "WallE",
      "WallBombW",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleE",
      "LockW",
      "LockE",
      "NoEntryW",
      "NoEntryE",
      "OneWayW",
      "OneWayE",
      "BossLockW",
      "BossLockE"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "item_roc1_05",
    "tags": {
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "WallS",
      "WallN",
      "WallBombS",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleN",
      "LockS",
      "LockN",
      "NoEntryS",
      "NoEntryN",
      "OneWayS",
      "OneWayN",
      "BossLockS",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 5
  },
  {
    "name": "item_roc1_06",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 2
  },
  {
    "name": "item_roc1_07",
    "tags": {
      "directionRequired": "ns",
      "fromE": "",
      "fromN": "ns",
      "fromS": "ns",
      "fromW": "",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallS",
      "WallN",
      "WallBombS",
      "WallBombN",
      "WallBombVisibleS",
      "WallBombVisibleN",
      "LockS",
      "LockN",
      "NoEntryS",
      "NoEntryN",
      "OneWayS",
      "OneWayN",
      "BossLockS",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 7
  },
  {
    "name": "item_roc1_08",
    "tags": {
      "directionRequired": "es",
      "fromE": "es",
      "fromN": "",
      "fromS": "es",
      "fromW": "",
      "itemRequired": "roc1",
      "letter": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "WallS",
      "WallE",
      "WallBombS",
      "WallBombE",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "LockS",
      "LockE",
      "NoEntryS",
      "NoEntryE",
      "OneWayS",
      "OneWayE",
      "BossLockS",
      "BossLockE"
    ],
    "chest": true,
    "complexity": 7
  },
  {
    "name": "item_roc1_ban_01",
    "tags": {
      "fromE": "",
      "fromN": "n",
      "fromS": "",
      "fromW": "",
      "itemBanned": "roc1",
      "letter": "ib"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Chest",
      "WallBombN",
      "WallBombVisibleN",
      "NoEntryN"
    ],
    "chest": true,
    "complexity": 4
  },
  {
    "name": "km_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "km,lm",
      "multiRoomLockCount": "4",
      "multiRoomType": "monsters"
    },
    "layers": [
      "Base",
      "Walls",
      "Enemies",
      "Decoration",
      "LockNo4",
      "LockNo3",
      "LockNo2",
      "LockNo1",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "MiniBossLockW",
      "MiniBossLockS",
      "MiniBossLockE",
      "MiniBossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "kp_00",
    "tags": {
      "entranceRequired": "s",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "kp_01_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp",
      "puzzleID": "1"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "kp_01_02",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp",
      "puzzleID": "1"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "kp_02_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp",
      "puzzleID": "2"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "kp_03_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp",
      "puzzleID": "3"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "kp_03_02",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp",
      "puzzleID": "3"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "kp_04_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "kp",
      "puzzleID": "4"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "lf_01",
    "tags": {
      "exitRequired": "n",
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "itemRequired": "roc1",
      "letter": "lf"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ExitW",
      "ExitE",
      "WallS",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "LockW",
      "LockS",
      "LockE",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 4
  },
  {
    "name": "lm_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "lm",
      "multiRoomLockCount": "5",
      "multiRoomType": "slates"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "lm_02",
    "tags": {
      "fromE": "ew",
      "fromN": "",
      "fromS": "",
      "fromW": "ew",
      "letter": "lm",
      "multiRoomLockCount": "4",
      "multiRoomType": "keys"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration"
    ],
    "chest": false,
    "complexity": 4
  },
  {
    "name": "lm_03",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "lm",
      "multiRoomLockCount": "4",
      "multiRoomType": "keys"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "lp_01_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "lp",
      "puzzleID": "1"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "lp_02_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "lp",
      "puzzleID": "2"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "lp_03_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "lp",
      "puzzleID": "3"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "lp_04_01",
    "tags": {
      "fromE": "nesw",
      "fromN": "nesw",
      "fromS": "nesw",
      "fromW": "nesw",
      "letter": "lp",
      "puzzleID": "4"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN",
      "LockPuzzleW",
      "LockPuzzleS",
      "LockPuzzleE",
      "LockPuzzleN"
    ],
    "chest": false,
    "complexity": 1
  },
  {
    "name": "obs_01",
    "tags": {
      "fromE": "new",
      "fromN": "new",
      "fromS": "s",
      "fromW": "new",
      "letter": "n,ib",
      "observatory": "s"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitS",
      "ObstaclePitN",
      "ObstaclePitW",
      "ObstaclePitE",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "obs_02",
    "tags": {
      "fromE": "esw",
      "fromN": "n",
      "fromS": "esw",
      "fromW": "esw",
      "letter": "n,ib",
      "observatory": "n"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "obs_03",
    "tags": {
      "fromE": "e",
      "fromN": "nsw",
      "fromS": "nsw",
      "fromW": "nsw",
      "letter": "n,ib",
      "observatory": "e"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  },
  {
    "name": "obs_04",
    "tags": {
      "fromE": "nes",
      "fromN": "nes",
      "fromS": "nes",
      "fromW": "w",
      "letter": "n,ib",
      "observatory": "w"
    },
    "layers": [
      "Base",
      "Walls",
      "Collision",
      "Enemies",
      "Chest",
      "Decoration",
      "ObstaclePitW",
      "ObstaclePitS",
      "ObstaclePitE",
      "ObstaclePitN",
      "WallW",
      "WallS",
      "WallE",
      "WallN",
      "WallBombW",
      "WallBombS",
      "WallBombE",
      "WallBombN",
      "WallBombVisibleW",
      "WallBombVisibleS",
      "WallBombVisibleE",
      "WallBombVisibleN",
      "LockW",
      "LockS",
      "LockE",
      "LockN",
      "NoEntryW",
      "NoEntryS",
      "NoEntryE",
      "NoEntryN",
      "OneWayW",
      "OneWayS",
      "OneWayE",
      "OneWayN",
      "BossLockW",
      "BossLockS",
      "BossLockE",
      "BossLockN"
    ],
    "chest": true,
    "complexity": 1
  }
]
